Added functions to close AutoHotKeys
cpdscrl/workshop-cli pull request #3
Opened 2024-05-06 12:39 UTC by Nkiblo

Added functions in all the files using the AutoHotKeys software to be sure that the used scripts are closed when not used.

2024-05-06 16:04 UTC, jborlido commented on workshop-cli/WorkshopCli/Actions/VideoAction.cs
> +            // Aguarde o término do processo VLC
O código e comentários são sempre em inglês. Estes casos eram comentários já escritos em pt ou foste tu que escreveste? Se não foste tu, faz o esforço para sempre que vejas estes casos mudar para inglês.

2024-05-06 16:58 UTC, Nkiblo commented on workshop-cli/WorkshopCli/Actions/VideoAction.cs
> +            // Aguarde o término do processo VLC
Fui eu. Ok vou estar atento a isso!

2024-05-27 10:55 UTC, jborlido requested changes

2024-05-27 10:55 UTC, jborlido commented on workshop-cli/WorkshopCli/Actions/VideoAction.cs
> +            // Aguarde o término do processo VLC
Ainda tens os comentários em português. Muda para inglês.

2024-05-27 10:55 UTC, jborlido commented on workshop-cli/WorkshopCli/OpenVSCode.cs
> +                    // Ignore any process that throws an exception when accessing MainModule
Que exceção é que estamos a ignorar? Ignorar exceções não as resolve.
Quando muito devemos dar catch de exceções específicas e lidar com elas diretamente, neste momento estás a apanhar todas as exceptions e a ignorar tudo, o que é perigoso.

2024-05-28 10:36 UTC, jborlido approved these changes

2024-05-28 10:36 UTC, merged